#!/bin/bash

set -e

# Install the Shepherd service file and ensure that the store path won't be
# garbage-collected as long as it's installed.
mkdir -p /etc/shepherd
unit_path=/etc/shepherd/non-nixos-gpu.scm
ln -sf @@resources@@/non-nixos-gpu.scm "$unit_path"
ln -sf "$unit_path" "@@statedir@@"/gcroots/non-nixos-gpu.scm

herd reload root /etc/shepherd/non-nixos-gpu.scm
